/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        error: '#ffb4ab',
        'surface-container-highest': '#36333e',
        'surface-tint': '#cdbdff',
        'on-secondary': '#00344f',
        'inverse-surface': '#e6e0ee',
        'on-surface': '#e6e0ee',
        outline: '#948da2',
        'secondary-fixed-dim': '#8dcdff',
        'secondary-container': '#00affe',
        'on-primary': '#370096',
        'on-surface-variant': '#cbc3d9',
        'on-error': '#690005',
        'on-background': '#e6e0ee',
        'primary-fixed-dim': '#cdbdff',
        surface: '#14121b',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#8f003f',
        'on-primary-fixed-variant': '#4f00d0',
        tertiary: '#ffb1c1',
        'on-error-container': '#ffdad6',
        'outline-variant': '#494456',
        'inverse-primary': '#6833ea',
        'on-secondary-fixed': '#001e30',
        'on-primary-container': '#cebfff',
        'on-primary-fixed': '#20005f',
        'surface-container-high': '#2b2933',
        'primary-fixed': '#e8deff',
        'surface-variant': '#36333e',
        'inverse-on-surface': '#322f39',
        'secondary-fixed': '#cae6ff',
        'surface-container-low': '#1c1a24',
        'surface-bright': '#3b3842',
        'on-secondary-fixed-variant': '#004b70',
        'tertiary-fixed-dim': '#ffb1c1',
        'on-tertiary-fixed': '#3f0018',
        'surface-container-lowest': '#0f0d16',
        'surface-dim': '#14121b',
        'on-tertiary': '#66002a',
        background: '#14121b',
        secondary: '#8dcdff',
        primary: '#cdbdff',
        'surface-container': '#211e28',
        'primary-container': '#5d21df',
        'on-secondary-container': '#003f5f',
        'tertiary-container': '#a8004b',
        'tertiary-fixed': '#ffd9df',
        'on-tertiary-container': '#ffb4c3',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      boxShadow: {
        'nav-glow': '0 0 64px rgba(98, 0, 238, 0.06)',
        'panel-glow': '0 0 64px rgba(98, 0, 238, 0.12)',
        orb: '0 20px 40px rgba(93, 33, 223, 0.3)',
      },
    },
  },
  plugins: [],
};
